In [1]:
# Numpy
import numpy as np

In [5]:
arr = np.array([[1,2,3],[4,5,6]])

In [7]:
arr.size

6

In [8]:
arr.shape

(2, 3)

In [9]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

# Reshape

In [10]:
# it return new array
arr = arr.reshape(3,2)

In [11]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

# Slicing

In [15]:
# slicing is same as list slicing
arr[2,1]

6

# Linspace

In [20]:
# 3 parameters range 2 to 10 both including, take 5 values
lin = np.linspace(2,10,5)

In [21]:
lin

array([ 2.,  4.,  6.,  8., 10.])

# min, max and sum

In [23]:
arr.min()

1

In [24]:
arr.max()

6

In [25]:
arr.sum()

21

# Array axis

In [27]:
# axis = 0 means rows.
# arr.min(axis = 0 ) means minumum row among all rows
arr.min(axis = 0)

array([1, 2])

In [30]:
# arr.min(axis = 1) means minimum among all columns
arr.min(axis = 1)

array([1, 3, 5])

# Square root and standard deviation

In [31]:
np.sqrt(arr)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [32]:
np.std(arr)

1.707825127659933

# Array stacking

In [33]:
# numpy provides horizontal and vertical stacking
a = np.array([[1,2,30],[10,15,4]])  
b = np.array([[1,2,3],[12, 19, 29]])  

In [35]:
np.vstack((a,b))

array([[ 1,  2, 30],
       [10, 15,  4],
       [ 1,  2,  3],
       [12, 19, 29]])

In [36]:
np.hstack((a,b))

array([[ 1,  2, 30,  1,  2,  3],
       [10, 15,  4, 12, 19, 29]])

# Array creation

In [42]:
# all zeros
zero = np.zeros((3,2), dtype = int)

In [43]:
zero

array([[0, 0],
       [0, 0],
       [0, 0]])

In [124]:
z = np.zeros(6)

In [125]:
z

array([0., 0., 0., 0., 0., 0.])

In [44]:
# all ones
one = np.ones((3,2),dtype = float)

In [45]:
one

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

# Numpy array with range

In [61]:
# arange(start,stop,step,dtype)
arr2 = np.arange(2,10,0.5,float)

In [62]:
arr2

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. ,
       8.5, 9. , 9.5])

# Transpose

In [63]:
transpose = arr2.T

In [64]:
transpose

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. ,
       8.5, 9. , 9.5])

# Bitwise operations

In [65]:
a = 10  
b = 12  

In [66]:
# binary representation
bin(a)

'0b1010'

In [67]:
# bitwise and
np.bitwise_and(a,b)

8

In [69]:
# bitwise or
# either value or variable is passed
np.bitwise_or(12,4)

12

In [71]:
# Invert operation
# 2`s compliment
np.invert(a)

-11

# Numpy mathematical funtions

In [74]:
# np.around(num,decimal) num is original number and decimal is the number of places
np.around(arr,2) # input must be array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [75]:
# floor function
np.floor(arr)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [77]:
# ceil function
np.ceil(arr)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

# Sort

In [79]:
# different sorting are there in numpy like mergesort(), quicksort() and heapsort()
# np.sort(array,axis,kind,order)
# kind means which algo. default is quick sort
# axis = 0 is row
a = np.array([[10,2,3],[4,5,6],[7,8,9]])
np.sort(a)# default is column

array([[ 2,  3, 10],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [80]:
np.sort(a,0)

array([[ 4,  2,  3],
       [ 7,  5,  6],
       [10,  8,  9]])

# Array

In [83]:
# create 2d array from exisiting elements
arr=np.array([1,2.,3.],ndmin=2)  

In [84]:
arr

array([[1., 2., 3.]])

In [89]:
arr=np.array([12,45.,3.],dtype=complex) 

In [90]:
arr

array([12.+0.j, 45.+0.j,  3.+0.j])

In [91]:
# to create 2d array 2 square brackets each for one tuple
arr=np.array([[1,2.,3.],[4.,5.,7]])  

In [92]:
arr

array([[1., 2., 3.],
       [4., 5., 7.]])

# Concat()

In [93]:
x=np.array([[1,2],[3,4]])  
y=np.array([[12,30]])  
z=np.concatenate((x,y)) 

In [94]:
z

array([[ 1,  2],
       [ 3,  4],
       [12, 30]])

In [98]:
z=np.concatenate((x,y.T), axis = 1) 

In [99]:
z

array([[ 1,  2, 12],
       [ 3,  4, 30]])

In [100]:
z=np.concatenate((x,y), axis=None) 
z

array([ 1,  2,  3,  4, 12, 30])

# Append

In [101]:
a=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])  
b=np.array([[11, 21, 31], [42, 52, 62], [73, 83, 93]])  
c=np.append(a,b)
c

array([10, 20, 30, 40, 50, 60, 70, 80, 90, 11, 21, 31, 42, 52, 62, 73, 83,
       93])

In [102]:
a=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])  
b=np.array([[11, 21, 31], [42, 52, 62], [73, 83, 93]])  
c=np.append(a,b,axis=0)
c

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90],
       [11, 21, 31],
       [42, 52, 62],
       [73, 83, 93]])

In [103]:
a=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])  
b=np.array([[11, 21, 31], [42, 52, 62], [73, 83, 93]])  
c=np.append(a,b,axis=1)
c

array([[10, 20, 30, 11, 21, 31],
       [40, 50, 60, 42, 52, 62],
       [70, 80, 90, 73, 83, 93]])

# Reshape

In [104]:
a = ([[10,30], [40,50],[70,80]])
b = np.reshape(a,(2,3))

In [105]:
b

array([[10, 30, 40],
       [50, 70, 80]])

# Sum

In [108]:
b = np.sum(a)
b

280

In [109]:
row = np.sum(a, axis = 0)
row

array([120, 160])

In [111]:
col = np.sum(a, axis = 1)
col

array([ 40,  90, 150])

In [112]:
a

[[10, 30], [40, 50], [70, 80]]

# Permutation

In [115]:
# 1. shuffle()
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [121]:
np.random.shuffle(a)
a

array([ 0,  2,  5, 13,  7,  8,  1,  9,  3, 12, 10,  6, 14,  4, 11])

In [122]:
# permutation
a = np.random.permutation(12)
a

array([ 1,  8,  4,  5,  3,  2,  6, 10,  7,  0, 11,  9])

# Distribution

In [123]:
# binomial distribution
# binomial(n, p[, size])
n, p = 10, .6  
s1= np.random.binomial(n, p, 10)  
s1  

array([6, 5, 6, 5, 7, 7, 6, 8, 6, 8])

# Where 

In [127]:
# np.where(cond,a,b)
# it select a function based on condition given
# return type is array
a = np.arange(15)
b = np.where(a>7,a,a*3) # a>7 is condition if true a executes otherwise a*3
b

array([ 0,  3,  6,  9, 12, 15, 18, 21,  8,  9, 10, 11, 12, 13, 14])

# Unique

In [128]:
a=np.unique([1,2,3,4,3,6,2,4])  
a  

array([1, 2, 3, 4, 6])

In [129]:
a = np.array([[1, 1, 0], [1, 1, 0], [2, 3, 4],[5, 9, 8],[2, 3, 4]])  
a  
b=np.unique(a, axis=0)  
b  

array([[1, 1, 0],
       [2, 3, 4],
       [5, 9, 8]])

# tolist

In [130]:
# It simply return copy of array element as python list.
# If we use a.tolist() for 1D array it is same as list(a), only differences is that tolist converts 
# numpy scalars to python scalars.
a = np.uint32([1, 2])
a_list = list(a)
a_list

[1, 2]

In [131]:
type(a_list[0])

numpy.uint32

In [132]:
a_tolist = a.tolist()
a_tolist

[1, 2]

In [133]:
type(a_tolist[0])

int

In [134]:
# For 2D array
a = np.array([[1, 2], [3, 4]])
list(a)

[array([1, 2]), array([3, 4])]

In [135]:
a.tolist()

[[1, 2], [3, 4]]

# Clip() function

In [136]:
# np.clip(a,min,max) array a if value > max then max and if value < min then min value is returned
a = np.arange(15)
b = np.clip(a,5,10)
b

array([ 5,  5,  5,  5,  5,  5,  6,  7,  8,  9, 10, 10, 10, 10, 10])

In [138]:
a = np.reshape(a,(3,5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [139]:
# for 2D array
b = np.clip(a,5,10)
b

array([[ 5,  5,  5,  5,  5],
       [ 5,  6,  7,  8,  9],
       [10, 10, 10, 10, 10]])

# flatten() function

In [140]:
# if we want 1D array rather than multi dimensional array then np.flatten() is used
a = np.arange(15)
a = np.reshape(a,(5,3))
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [142]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# np.meshgid()

In [145]:
# numpy module provide meshgrid function of 1D array
a = np.linspace(1, 2, 5)  
b = np.linspace(1, 2, 10)  
mesh_a, mesh_b = np.meshgrid(a, b)
mesh_a, mesh_b

(array([[1.  , 1.25, 1.5 , 1.75, 2.  ],
        [1.  , 1.25, 1.5 , 1.75, 2.  ],
        [1.  , 1.25, 1.5 , 1.75, 2.  ],
        [1.  , 1.25, 1.5 , 1.75, 2.  ],
        [1.  , 1.25, 1.5 , 1.75, 2.  ],
        [1.  , 1.25, 1.5 , 1.75, 2.  ],
        [1.  , 1.25, 1.5 , 1.75, 2.  ],
        [1.  , 1.25, 1.5 , 1.75, 2.  ],
        [1.  , 1.25, 1.5 , 1.75, 2.  ],
        [1.  , 1.25, 1.5 , 1.75, 2.  ]]),
 array([[1.        , 1.        , 1.        , 1.        , 1.        ],
        [1.11111111, 1.11111111, 1.11111111, 1.11111111, 1.11111111],
        [1.22222222, 1.22222222, 1.22222222, 1.22222222, 1.22222222],
        [1.33333333, 1.33333333, 1.33333333, 1.33333333, 1.33333333],
        [1.44444444, 1.44444444, 1.44444444, 1.44444444, 1.44444444],
        [1.55555556, 1.55555556, 1.55555556, 1.55555556, 1.55555556],
        [1.66666667, 1.66666667, 1.66666667, 1.66666667, 1.66666667],
        [1.77777778, 1.77777778, 1.77777778, 1.77777778, 1.77777778],
        [1.88888889, 1.88888889, 1.888

# standard deviation

In [146]:
a = np.array([[1,6,45,3],[8,5,32,11]])
std = np.std(a)
std

14.852924796147054